export const invoiceConstants = {
    SET_INVOICE: 'SET_INVOICE',
    EDIT_INVOICE: 'EDIT_INVOICE',
    SET_PRODUCT_ITEMS: 'SET_PRODUCT_ITEMS_INVOICE',
    SET_PRODUCT_ITEM: 'SET_PRODUCT_ITEM_INVOICE',
    ADD_PRODUCT_ITEM: 'ADD_PRODUCT_ITEM_INVOICE',
    DELETE_PRODUCT_ITEM: 'DELETE_PRODUCT_ITEM_INVOICE'
};